### ISSUE TITLE
Several Templates still show Default Years

### ISSUE THREAD

**Issue by smiths** [smiths/MEASURE#71]
When selecting the specific year for the "Course Info Maintenance Template" and the "Course Report" the dialog box shows the default year.  This behaviour was changed for the other templates and should probably be changed here too.

**Comment by EvanVena** [comment]
Done, please check.

**Comment by smiths** [comment]
Hello Evan.  I have checked and all of the templates that we are using no longer show the default year.  Some of the templates that we are no longer using, like ContinuousImprovementPlanTemplateV1.xlsm still show the default year, but since we are not using them, this is not a problem.  I'll close this issue.
